remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Markdown Badges
relative_links:
  enabled: true
  collections: true
description: A Curated List of Badges for GitHub Projects & Profiles
