remote_theme : "jekyll/minima"

minima:
  skin: dark

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

locale : "en-US"
title: "Markdown Badges"
title_separator : "-"

relative_links:
  enabled: true
  collections: true
  
description: "A Curated List of Badges for GitHub Projects & Profiles"
teaser: "/assets/banner.png"

markdown: kramdown
